### ISSUE TITLE
Does stepping on infected draw more? Why does it feel like more infected always come?

### ISSUE THREAD

**Issue by VinceHPicton** [SirDoggyJvla/The-Last-of-Us-Infected#10]
Hey, amazing work btw! Just the 2 questions in title. I notice you put in the mod description "don't step on the infected" and wondered  why.

**Comment by SirDoggyJvla** [comment]
Hey no that doesn't attract other infected. Stepping on the infected will push you back

**Comment by SirDoggyJvla** [comment]
Most definitely the super hearing doing that

**Comment by VinceHPicton** [comment]
Ok cheers, let me know if you want any help with the mod, I don't know the lua language but I could definitely write some more detailed descriptions for your steam page if you want me to.

I noticed that bloaters are exceptionally easy to kill using a vehicle - just as easy as a runner, appreciate you probably know this already and it's probably really hard to fix, but i thought I may aswell let you know anyway.
