### ISSUE TITLE
Stalkers vision

### ISSUE THREAD

**Issue by miklav21** [SirDoggyJvla/The-Last-of-Us-Infected#7]
Hi! I am trying out this mod for my server and I love everything about it apart clickers beign able to see us from a mile away. Was tested with good stealth and lightfoot and none and not much difference. is there any known issues about this?
Thanks

**Comment by SirDoggyJvla** [comment]
https://youtu.be/GqNbaCQ2JLM?si=mYpAdt_B5B3uvanR

**Comment by miklav21** [comment]
That explains it a bit thanks
